package view;

import backend.Classroom;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import data.DataContainer;

public class ClassroomReportForm extends javax.swing.JFrame {

    /**
     * Creates new form
     */
    public ClassroomReportForm(DataContainer data) {

        // Initialize the form
        initComponents();
        
        // Retrieve the list from the data model
        ArrayList<Classroom> listOfClassrooms = data.getListOfClassrooms();

  

        // Call method that will add all classrooms to the table
        this.populateTable(listOfClassrooms);

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        textAreaOfClassroomsScrollPanel = new javax.swing.JScrollPane();
        tableOfClassrooms = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("List Of Classrooms At A Glance");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(275, 20, 210, 16);

        closeButton.setText("Back to Main Menu");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(closeButton);
        closeButton.setBounds(290, 200, 160, 32);

        textAreaOfClassroomsScrollPanel.setBackground(new java.awt.Color(255, 255, 255));

        tableOfClassrooms.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Room Number", "Room Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableOfClassrooms.setColumnSelectionAllowed(true);
        textAreaOfClassroomsScrollPanel.setViewportView(tableOfClassrooms);
        tableOfClassrooms.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (tableOfClassrooms.getColumnModel().getColumnCount() > 0) {
            tableOfClassrooms.getColumnModel().getColumn(0).setResizable(false);
            tableOfClassrooms.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(textAreaOfClassroomsScrollPanel);
        textAreaOfClassroomsScrollPanel.setBounds(10, 50, 720, 138);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

  

    /**
     * Private method that will add all classrooms to the table
     */
    private void populateTable(ArrayList<Classroom> listOfClassrooms) {

        // A table model like this will hold the data for the JTable (this is the M in MVC)
        DefaultTableModel defaultTableModel = new DefaultTableModel();

        // add columns to table model
        defaultTableModel.addColumn("Room Number");
        defaultTableModel.addColumn("Room Type");

        // Link the data model to the table
        tableOfClassrooms.setModel(defaultTableModel);

        // Add the classrooms in the ArrayList to the table model
        for (Classroom aClassroom : listOfClassrooms) {

            // Create a vector that is one row in the table
            Vector aClassroomForTable = new Vector();

            // Add the data to the vector
            aClassroomForTable.add(aClassroom.getRoomNumber());
            aClassroomForTable.add(aClassroom.getTypeOfRoom());

            // Add the vector to the  data model that is connected to the JTable
            defaultTableModel.addRow(aClassroomForTable);

            tableOfClassrooms.setModel(defaultTableModel);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable tableOfClassrooms;
    private javax.swing.JScrollPane textAreaOfClassroomsScrollPanel;
    // End of variables declaration//GEN-END:variables
}
