/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import backend.Faculty;
import backend.FacultyCourse;
import backend.Student;
import backend.StudentCourse;
import data.DataContainer;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author BenMorrisRains
 */
public class FacultyReportForm extends javax.swing.JFrame {

    /**
     * Creates new form FacultyReportForm
     */
    public FacultyReportForm(DataContainer data) {
        initComponents();

        ArrayList<Faculty> listOfFaculty = data.getListOfFaculty();

        this.populateTable(listOfFaculty);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOfFaculty = new javax.swing.JTable();
        exitbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Faculty Information:");

        tableOfFaculty.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name:", "Address:", "SSN:", "Date of Birth:", "Date of Hire:", "Date of Termination:", "Salary: ", "Status:", "List of Classes:"
            }
        ));
        jScrollPane1.setViewportView(tableOfFaculty);

        exitbutton.setText("Back to Main Menu");
        exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(275, 275, 275)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(exitbutton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitbutton)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbuttonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitbuttonActionPerformed

    private void populateTable(ArrayList<Faculty> listOfFaculty) {

        // A table model like this will hold the data for the JTable (this is the M in MVC)
        DefaultTableModel defaultTableModel = new DefaultTableModel();

        // add columns to table model
        defaultTableModel.addColumn("Name");
        defaultTableModel.addColumn("Address");
        defaultTableModel.addColumn("Date of Birth");
        defaultTableModel.addColumn("Date of Hire:");
        defaultTableModel.addColumn("Date of Termination:");
        defaultTableModel.addColumn("Salary:");
        defaultTableModel.addColumn("SSN:");
        defaultTableModel.addColumn("Status");
        defaultTableModel.addColumn("List of Classes:");

        // Link the data model to the table
        tableOfFaculty.setModel(defaultTableModel);

        // Add the classrooms in the ArrayList to the table model
        for (Faculty aFaculty : listOfFaculty) {

            // Create a vector that is one row in the table
            Vector aClassroomForTable = new Vector();

            // Add the data to the vector
            aClassroomForTable.add(aFaculty.getName());
            aClassroomForTable.add(aFaculty.getAddress());
            aClassroomForTable.add(aFaculty.getDateOfBirth());
            aClassroomForTable.add(aFaculty.getDateOfHire());
            aClassroomForTable.add(aFaculty.getDateOfTermination());
            aClassroomForTable.add(aFaculty.getSalary());
            aClassroomForTable.add(aFaculty.getSocialSecurityNumber());
            aClassroomForTable.add(aFaculty.getStatus());
            aClassroomForTable.add(aFaculty.getListOfCourses());

            String courseText = "";
            ArrayList<FacultyCourse> courses = aFaculty.getListOfCourses();
            for (FacultyCourse course : courses) {
                courseText = courseText + course.getCourseId() + ",";
            }
            // Add the vector to the  data model that is connected to the JTable
            defaultTableModel.addRow(aClassroomForTable);

            tableOfFaculty.setModel(defaultTableModel);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableOfFaculty;
    // End of variables declaration//GEN-END:variables
}
